steps:

- name: node:22
  entrypoint: npm
  args: [ 'install' ]

- name: node:22
  entrypoint: npm
  args: [ 'run', 'build' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/hello-vue3:$COMMIT_SHA', '-f', 'Dockerfile', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/hello-vue3:$COMMIT_SHA' ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'hello-vue3',
    '--image', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/hello-vue3:$COMMIT_SHA',
    '--project', '$PROJECT_ID',
    '--region', 'asia-south1',
    '--platform', 'managed',
    '--port', '80',
    '--memory', '128Mi',
    '--cpu', '1',
    '--timeout', '1',
    '--concurrency', '10',
    '--min-instances', '0',
    '--max-instances', '1'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
